[cr148] Preemtping unwanted replacement for `MultiContentsView`
Due to recent header additions to this class, a build error started
occurring due to an unwanted substitution.

```
../../content/public/browser/web_contents_observer.h:922:16: error: duplicate 'virtual' declaration specifier [-Werror,-Wduplicate-decl-specifier]
  922 |   virtual void OnWebContentsFocused(RenderWidgetHost* render_widget_host) {}
      |                ^
../../brave/chromium_src/chrome/browser/ui/views/frame/multi_contents_view.h:15:30: note: expanded from macro 'OnWebContentsFocused'
   15 | #define OnWebContentsFocused virtual OnWebContentsFocused
      |                              ^
1 error generated.
```

Chromium changes:
https://chromium.googlesource.com/chromium/src/+/9b1a481b8d0dab06a5c20bde25faa00cc6417c8c

commit 9b1a481b8d0dab06a5c20bde25faa00cc6417c8c
Author: Eshwar Stalin <estalin@chromium.org>
Date:   Wed Apr 1 15:50:32 2026 -0700

    [SxS] Minor cleanup of SplitTabHighlightController

    Having the delegate interface directly implemented by the view and
    passing the delegate directly into the controller class. This is more
    modular and more aligned to the design principles.

    Change-Id: I83797b7d82939ac69456852c3ca0e862132257b9
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7720599
    Reviewed-by: Steven Luong <stluong@chromium.org>
    Commit-Queue: Eshwar Stalin <estalin@chromium.org>
    Cr-Commit-Position: refs/heads/main@{#1608832}